### ISSUE TITLE
date error

### ISSUE THREAD

**Issue by dorkmo** [fenwick67/cabal-clone#1]
![image](https://user-images.githubusercontent.com/1923070/55766647-2ca39880-5a3b-11e9-97a3-f41a689bf265.png)

date is off by a month?

**Comment by fenwick67** [comment]
Sorry I missed the notification for this, I'll look into it sometime next week

**Comment by fenwick67** [comment]
There were two Mays in my month array 😐 . It's fixed now.

I need to update some dependencies and then I'll throw a new release together.
